import assert from "node:assert/strict";
import test from "node:test";

import { validationHtml } from "./ui.js";

test("sauvegarde un commentaire sans reconstruire la carte et perdre le focus", () => {
  const html = validationHtml();
  assert.match(html, /async function saveItem\(id, patch, rerender=true\)/u);
  assert.match(html, /saveItem\(id,\{note:value\},false\)/u);
  assert.match(html, /if \(rerender\) render\(\);/u);
  assert.match(html, /data-category="live">● Direct/u);
  assert.doesNotMatch(html, /data-category="uncertain">À confirmer/u);
  assert.match(html, /async function loadDate\(date=''\)/u);
  assert.match(html, /data-date=/u);
  assert.match(html, /timeRangeLabel\|\|b\.timeLabel/u);
  assert.match(html, /function diversifiedSelection\(items,limit\)/u);
  assert.match(html, /data-view="events">À voir/u);
  assert.match(html, /Diffuseur non identifié/u);
  assert.match(html, /function renderEventGroups\(items,report\)/u);
  assert.match(html, /function renderEventSelection\(items,report\)/u);
  assert.match(html, /details class="sport-group" data-sport-group=/u);
  assert.match(html, /summary class="sport-heading"/u);
  assert.match(html, /class="summary-footer" id="summary"/u);
  assert.match(html, /details class="exhaustivity-details"/u);
  assert.doesNotMatch(html, /details class="exhaustivity-details" open/u);
  assert.match(html, /\.event-line > \.broadcasts/u);
  assert.match(html, /\.secondary-details > summary::before/u);
  assert.match(html, /const detailsLabel=eventFirst/u);
  assert.match(html, /function channelTone\(values\)/u);
  assert.match(html, /Diffusions :/u);
  assert.match(html, /event-schedule/u);
  assert.match(html, /map\(abbreviateFirstName\)/u);
  assert.match(html, /function abbreviateFirstName\(value\)/u);
  assert.match(html, /eventRoundLabel/u);
  assert.match(html, /entry\.roundLabel/u);
  assert.match(html, /split\(\/\\s\+\/\)/u);
  assert.doesNotMatch(html, /split\(\/s\+\/\)/u);
  assert.match(html, /dayOffset===0\?time:'J'/u);
  assert.match(html, /Détails et validation ponctuelle/u);
  assert.doesNotMatch(html, /id="refresh"/u);
  assert.match(html, /data-period="now">Maintenant/u);
  assert.match(html, /data-period="evening">Ce soir/u);
  assert.match(html, /Personnaliser et diagnostiquer/u);
  assert.match(html, /Qualité des données et signaler un manque/u);
  assert.match(html, /Couverture EPG des chaînes prioritaires/u);
  assert.match(html, /function renderCoverage\(\)/u);
  assert.doesNotMatch(html, /async function refreshReports()/u);
  assert.match(html, /async function checkForUpdatedReport\(\)/u);
  assert.match(html, /300_000/u);
  assert.match(html, /Mes sports et mes bouquets/u);
  assert.match(html, /sporttoday-preferences-v2/u);
  assert.match(html, /version:2, excludedSports:\[\], packages:\[\]/u);
  assert.doesNotMatch(html, /keepUnmatched/u);
  assert.match(html, /data-preference-mode="preferences">Ma sélection/u);
  assert.match(html, /data-preference-mode="all">Tout voir/u);
  assert.match(html, /function allPreferenceOptions\(\)/u);
  assert.match(html, /function canonicalSport\(value\)/u);
  assert.match(html, /À regarder maintenant/u);
  assert.match(html, /for\(const sport of preferences\.excludedSports\) sports\.add\(sport\)/u);
  assert.match(html, /function matchesChannelPreference\(broadcast\)/u);
  assert.match(html, /function filterPreferredBroadcasts\(item\)/u);
  assert.match(html, /item\.broadcasts\.length===0\) return null/u);
  assert.doesNotMatch(html, /data-preference-unmatched/u);
  assert.match(html, /Les événements sans diffuseur restent disponibles dans l.exhaustivité/u);
  assert.match(html, /matchesBroadcast\(item,broadcast,report\)&&matchesChannelPreference\(broadcast\)/u);
  assert.match(html, /Ces choix restent sur cet appareil/u);
  assert.match(html, /function packageForName\(value\)/u);
  assert.match(html, /function isFrenchBroadcast\(broadcast\)/u);
  assert.match(html, /function highlightSelection\(items\)/u);
  assert.match(html, /function broadcastTrustLabel\(values\)/u);
  assert.match(html, /Sélection générée à/u);
  assert.match(html, /hoursUntilStart/u);
});
